# Trading configuration
INSTRUMENTS = ["NSE_INDEX|Nifty 50", "NSE_INDEX|Nifty Bank"]
PAPER_TRADING = True
USE_ADVANCED_VOLUME_ANALYSIS = True

# Strategy thresholds
SCORE_THRESHOLD = 7
PROBABILITY_THRESHOLD = 75
